globals:
  codebase_name: mmseg
  codebase_dir: ../mmsegmentation
  checkpoint_force_download: False
  checkpoint_dir: ../mmdeploy_checkpoints
  images:
    img_leftImg8bit: &img_leftImg8bit ../mmsegmentation/tests/data/pseudo_cityscapes_dataset/leftImg8bit/frankfurt_000000_000294_leftImg8bit.png
    img_loveda_0: &img_loveda_0 ../mmsegmentation/tests/data/pseudo_loveda_dataset/img_dir/0.png
    img_loveda_1: &img_loveda_1 ../mmsegmentation/tests/data/pseudo_loveda_dataset/img_dir/1.png
    img_loveda_2: &img_loveda_2 ../mmsegmentation/tests/data/pseudo_loveda_dataset/img_dir/2.png
    img_potsdam: &img_potsdam ../mmsegmentation/tests/data/pseudo_potsdam_dataset/img_dir/2_10_0_0_512_512.png
    img_vaihingen: &img_vaihingen ../mmsegmentation/tests/data/pseudo_vaihingen_dataset/img_dir/area1_0_0_512_512.png
  metric_info: &metric_info
    mIoU: # named after metafile.Results.Metrics
      eval_name: mIoU # test.py --metrics args
      metric_key: mIoU # eval OrderedDict key name
      tolerance: 0.1
      task_name: Semantic Segmentation # metafile.Results.Task
      dataset: Cityscapes # metafile.Results.Dataset
  convert_image: &convert_image
    input_img: *img_leftImg8bit
    test_img: *img_loveda_0
  backend_test: &default_backend_test True
  sdk:
    sdk_dynamic_fp32: &sdk_dynamic_fp32 configs/mmseg/segmentation_sdk_dynamic.py

onnxruntime:
  pipeline_ort_static_fp32: &pipeline_ort_static_fp32
    convert_image: *convert_image
    deploy_config: configs/mmseg/segmentation_onnxruntime_static-512x512.py

  pipeline_ort_dynamic_fp32: &pipeline_ort_dynamic_fp32
    convert_image: *convert_image
    deploy_config: configs/mmseg/segmentation_onnxruntime_dynamic.py

tensorrt:
  pipeline_trt_static_fp32: &pipeline_trt_static_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt_static-1024x1024.py

  pipeline_trt_static_fp16: &pipeline_trt_static_fp16
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt-fp16_static-1024x1024.py

  pipeline_trt_static_int8: &pipeline_trt_static_int8
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt-int8_static-1024x1024.py


  pipeline_trt_dynamic_fp32: &pipeline_trt_dynamic_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt_dynamic-512x1024-2048x2048.py

  pipeline_trt_dynamic_fp16: &pipeline_trt_dynamic_fp16
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt-fp16_dynamic-512x1024-2048x2048.py

  pipeline_trt_dynamic_int8: &pipeline_trt_dynamic_int8
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmseg/segmentation_tensorrt-int8_dynamic-512x1024-2048x2048.py

openvino:
  pipeline_openvino_dynamic_fp32: &pipeline_openvino_dynamic_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    deploy_config: configs/mmseg/segmentation_openvino_dynamic-1024x2048.py

  pipeline_openvino_static_fp32: &pipeline_openvino_static_fp32
    convert_image: *convert_image
    backend_test: False
    deploy_config: configs/mmseg/segmentation_openvino_static-512x512.py

ncnn:
  pipeline_ncnn_static_fp32: &pipeline_ncnn_static_fp32
    convert_image: *convert_image
    backend_test: False
    deploy_config: configs/mmseg/segmentation_ncnn_static-512x512.py

pplnn:
  pipeline_ppl_dynamic_fp32: &pipeline_ppl_dynamic_fp32
    convert_image: *convert_image
    backend_test: False
    deploy_config: configs/mmseg/segmentation_pplnn_dynamic-1024x2048.py

  pipeline_ppl_static_fp32: &pipeline_ppl_static_fp32
    convert_image: *convert_image
    backend_test: False
    deploy_config: configs/mmseg/segmentation_pplnn_static-512x512.py

torchscript:
  pipeline_ts_fp32: &pipeline_ts_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    deploy_config: configs/mmseg/segmentation_torchscript.py


models:
  - name: deeplabv3
    metafile: configs/deeplabv3/deeplabv3.yml
    model_configs:
      - configs/deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes.py
    pipelines:
      - *pipeline_ort_dynamic_fp32
      - *pipeline_trt_dynamic_fp16
      - *pipeline_openvino_dynamic_fp32
      - *pipeline_ncnn_static_fp32
      - *pipeline_ppl_dynamic_fp32
      - *pipeline_ts_fp32
