globals:
  codebase_name: mmcls
  codebase_dir: ../mmclassification
  checkpoint_force_download: False
  checkpoint_dir: ../mmdeploy_checkpoints
  images:
    img_coco_224x224: &img_coco_224x224 ./tests/data/tiger.jpeg
    img_coco_300x300: &img_coco_300x300
    img_coco_800x1344: &img_coco_800x1344
    img_blank: &img_blank
  dataset_path:
    COCO:
      image:
      annotation:
  metric_info: &metric_info
    Top 1 Accuracy: # named after metafile.Metric
      eval_name: accuracy # test.py --metrics args
      metric_key: accuracy_top-1 # eval OrderedDict key name
      tolerance: 0.5
    Top 5 Accuracy:
      eval_name: accuracy
      metric_key: accuracy_top-5
      tolerance: 0.5
  convert_image: &convert_image
    input_img: *img_coco_224x224
    test_img: *img_coco_300x300
  backend_test: &default_backend_test True
  sdk:
    sdk_dynamic_fp32: &sdk_dynamic_fp32 configs/mmcls/classification_sdk_dynamic.py

onnxruntime:
  pipeline_ort_static_fp32: &pipeline_ort_static_fp32
    convert_image: *convert_image
    deploy_config: configs/mmcls/classification_onnxruntime_static.py

  pipeline_ort_dynamic_fp32: &pipeline_ort_dynamic_fp32
    convert_image: *convert_image
    deploy_config: configs/mmcls/classification_onnxruntime_dynamic.py

tensorrt:
  pipeline_trt_static_fp32: &pipeline_trt_static_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    deploy_config: configs/mmcls/classification_tensorrt_static-224x224.py

  pipeline_trt_dynamic_fp32: &pipeline_trt_dynamic_fp32
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmcls/classification_tensorrt_dynamic-224x224-224x224.py

  pipeline_trt_dynamic_fp16: &pipeline_trt_dynamic_fp16
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmcls/classification_tensorrt-fp16_dynamic-224x224-224x224.py

  pipeline_trt_dynamic_int8: &pipeline_trt_dynamic_int8
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmcls/classification_tensorrt-int8_dynamic-224x224-224x224.py

openvino:
ncnn:
pplnn:
torchscript:


models:
  - name: mobilenet_v2
    codebase_model_config_dir: ./configs/mobilenet_v2
    metafile: configs/mobilenet_v2/metafile.yml
    model_configs:
      - mobilenet-v2_8xb32_in1k.py
    pipelines:
      - *pipeline_ort_dynamic_fp32
      - *pipeline_trt_dynamic_fp16
