globals:
  codebase_name: mmcls
  codebase_dir: ../mmclassification
  checkpoint_force_download: False
  checkpoint_dir: ../mmdeploy_checkpoints
  deploy_config_dir: ./configs/mmcls
  dataset_path:
    COCO:
  metric_tolerance:
    Top 1 Accuracy: 0.01
    Top 5 Accuracy: 0.01

default_config: &default_config
  input_img_path: &default_input_img_path ./tests/data/tiger.jpeg
  dynamic_test_img_path: &default_dynamic_test_img_path
  sdk_config: &default_sdk_config
    deploy_config:
      static:
        fp32: &default_sdk_static_fp32
      dynamic:
        fp32: &default_sdk_dynamic_fp32 classification_sdk_dynamic.py
  backends:
    onnxruntime: &default_onnxruntime_config
      performance_align: False
      deploy_config:
        static:
          fp32: &default_onnxruntime_static_fp32 classification_onnxruntime_static.py
        dynamic:
          fp32: &default_onnxruntime_dynamic_fp32 classification_onnxruntime_dynamic.py
    tensorrt: &default_tensorrt_config
      performance_align: False
      deploy_config:
        static:
          fp32: &default_tensorrt_static_fp32 classification_tensorrt_static-224x224.py
          fp16: &default_tensorrt_static_fp16 classification_tensorrt-fp16_static-224x224.py
          int8: &default_tensorrt_static_int8 classification_tensorrt-int8_static-224x224.py
        dynamic:
          fp32: &default_tensorrt_dynamic_fp32 classification_tensorrt_dynamic-224x224-224x224.py
          fp16: &default_tensorrt_dynamic_fp16 classification_tensorrt-fp16_dynamic-224x224-224x224.py
          int8: &default_tensorrt_dynamic_int8 classification_tensorrt-int8_dynamic-224x224-224x224.py
    openvino: &default_openvino_config
      performance_align: False
      deploy_config:
        static:
          fp32: &default_openvino_static_fp32
        dynamic:
          fp32: &default_openvino_dynamic_fp32 classification_openvino_dynamic-224x224.py
    ncnn: &default_ncnn_config
      performance_align: False
      deploy_config:
        static:
          fp32: &default_ncnn_static_fp32 classification_ncnn_static.py
        dynamic:
          fp32: &default_ncnn_dynamic_fp32 classification_ncnn_dynamic.py
    pplnn: &default_pplnn_config
      performance_align: False
      deploy_config:
        static:
          fp32: &default_pplnn_static_fp32
        dynamic:
          fp32: &default_pplnn_dynamic_fp32 classification_pplnn_dynamic-224x224.py
    torchscript: &default_ts_config
      performace_align: False
      deploy_config:
        dynamic:
          fp32: &default_ts_dynamic_fp32 classification_torchscript.py

models:
  - name: mobilenet_v2
    codebase_model_config_dir: ./configs/mobilenet_v2
    model_configs:
      - mobilenet-v2_8xb32_in1k.py
    metafile: configs/mobilenet_v2/metafile.yml
    input_img_path: *default_input_img_path
    dynamic_test_img_path:
    calib_dataset_cfg:
    sdk_config:
      deploy_config:
        dynamic:
          fp32: *default_sdk_dynamic_fp32
    backends:
      onnxruntime:
        performance_align: False
        sdk_test: False
        deploy_config:
          dynamic:
            fp32: # *default_onnxruntime_dynamic_fp32
      tensorrt:
        performance_align: True
        sdk_test: True
        deploy_config:
          dynamic:
            fp32: *default_tensorrt_dynamic_fp32
            fp16: # *default_tensorrt_dynamic_fp16
            int8: # *default_tensorrt_dynamic_int8
      ncnn:
        performance_align: False
        sdk_test: False
        deploy_config:
          static:
            fp32:
          dynamic:
            fp32:
      openvino:
        performance_align: False
        sdk_test: False
        deploy_config:
          dynamic:
            fp32: # *default_openvino_dynamic_fp32
      pplnn:
        performance_align: False
        sdk_test: False
        deploy_config:
          dynamic:
            fp32: # *default_pplnn_dynamic_fp32
      torchscript:
        performace_align: False
        sdk_test: False
        dynamic_test_img_path:
        deploy_config:
          dynamic:
            fp32: # *default_ts_dynamic_fp32
