globals:
  codebase_name: mmedit
  codebase_dir: ../mmediting
  checkpoint_force_download: False
  checkpoint_dir: ../mmdeploy_checkpoints
  images:
    img_320x320: &img_320x320 ./tests/data/tiger.jpeg
    img_blank: &img_blank
  metric_info: &metric_info
    Set5: # named after metafile.Results.Metrics
      eval_name: '?' # test.py --metrics args
      metric_key: '?' # eval OrderedDict key name
      tolerance: 0.5
      task_name: Restorers # metafile.Results.Task
      dataset: DIV2K # metafile.Results.Dataset
  convert_image: &convert_image
    input_img: *img_320x320
    test_img: *img_blank
  backend_test: &default_backend_test True
  sdk:
    sdk_dynamic_fp32: &sdk_dynamic_fp32 configs/mmedit/super-resolution/super-resolution_sdk_dynamic.py

onnxruntime:
  pipeline_ort_static_fp32: &pipeline_ort_static_fp32
    convert_image: *convert_image
    deploy_config: configs/mmedit/super-resolution/super-resolution_onnxruntime_static.py

  pipeline_ort_dynamic_fp32: &pipeline_ort_dynamic_fp32
    convert_image: *convert_image
    deploy_config: configs/mmedit/super-resolution/super-resolution_onnxruntime_dynamic.py

tensorrt:
  pipeline_trt_dynamic_fp16: &pipeline_trt_dynamic_fp16
    convert_image: *convert_image
    backend_test: *default_backend_test
    sdk_config: *sdk_dynamic_fp32
    deploy_config: configs/mmedit/super-resolution/super-resolution_tensorrt-fp16_dynamic-32x32-512x512.py


models:
  - name: srcnn
    metafile: configs/restorers/srcnn/metafile.yml
    codebase_model_config_dir: configs/restorers/srcnn
    model_configs:
      - srcnn_x4k915_g1_1000k_div2k.py
    pipelines:
#      - *pipeline_ort_dynamic_fp32
      - *pipeline_trt_dynamic_fp16
